### ISSUE TITLE
mkdir: cannot create directory '/home/container_user/.vscode-server/bin

### ISSUE THREAD

**Issue by eloquent-peasant** [coredevel/nextjs-docker-compose#1]
Hello there
thanks a lot for this

after running the dc.sh script and then try to dev container: attach to running container

i get this permission error

```
[702 ms] Command in container failed: mkdir -p /home/container_user/.vscode-server/bin/fabdb6a30b49f79a7aba0f2ad9df9b399473380f_1734810444597
[702 ms] mkdir: cannot create directory '/home/container_user/.vscode-server/bin': Permission denied
[702 ms] Exit code 1
```

**Comment by coredevel** [comment]
Hey @eloquent-peasant, just seeing this now - I vaguely remember running into a perms issue too but can't remember if it was that, I'll take a look.

**Comment by eloquent-peasant** [comment]
@coredevel Hello there, I was able to fix the issue by fixing this permission issue in the docker file

```
 # Ensure the .vscode-server directory is owned by container_user
 RUN mkdir -p /home/container_user/.vscode-server
 RUN chown -R container_user:container_group /home/container_user/.vscode-server
```
